"""
cod 统一能力工作站工具类
设备名称: COD分析仪
设备描述: 化学需氧量测定仪主要用于测定水样中有机物等还原性物质的含量。其原理是在强酸性条件下，用一定量的重铬酸钾氧化水样中的还原性物质，通过测量氧化剂的消耗量来计算化学需氧量（COD）的值。COD 是衡量水体受有机物污染程度的重要指标之一。在环境监测中，通过 COD 测定仪可以快速、准确地检测地表水、工业废水等的污染状况，为水质评价和污染治理提供依据。
生成时间: 2025-11-07 19:42:38
"""

class UnifiedWorkstationTools:
    """统一能力工作站工具管理器"""
    
    def tool_cod(self, task_description: str, **params):
        """
        COD分析仪 - 化学需氧量测定仪主要用于测定水样中有机物等还原性物质的含量。其原理是在强酸性条件下，用一定量的重铬酸钾氧化水样中的还原性物质，通过测量氧化剂的消耗量来计算化学需氧量（COD）的值。COD 是衡量水体受有机物污染程度的重要指标之一。在环境监测中，通过 COD 测定仪可以快速、准确地检测地表水、工业废水等的污染状况，为水质评价和污染治理提供依据。
        
        可用操作:
        - 启动COD (start_cod): 启动COD
        - 停止COD (stop_cod): 停止COD
        - 样品下发 (sample_issuse): 样品下发
        - 获取样品结果 (obtain_result): 获取样品结果
        - 清空样品列表 (clear_sample_list): 清空样品列表
        - 录入样品信息 (enter_sample_info): 录入样品信息
        - 等待就绪 (wait_device_ready): 等待就绪
        - 批量下发样品 (send_sample_list): 批量下发样品
        - 容器分配 (wait_loop): 
        
        参数:
            task_description: 任务描述
            **params: 其他参数
        """
        # 根据任务描述执行相应的操作
        # 这里需要实现任务编排逻辑
        result = {
            "workstation": "COD分析仪",
            "task": task_description,
            "status": "pending_implementation",
            "message": "任务编排功能待实现 - 需要根据任务描述解析并执行相应的动作序列"
        }
        
        # 简单的任务匹配逻辑
        task_lower = task_description.lower()
        
        # 尝试匹配已有的动作
        matched_actions = []
        actions_list = [
    {
        "code": "start_cod",
        "id": 1897802271294492,
        "name": "启动COD",
        "noteCn": "启动COD",
        "noteEn": "start_cod",
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "start_cod",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "operate",
                "paramName": "指令编码",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/cod/operate"
        }
    },
    {
        "code": "stop_cod",
        "id": 1897802271294493,
        "name": "停止COD",
        "noteCn": "停止COD",
        "noteEn": "stop_cod",
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "stop_cod",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "stop_cod",
                "paramName": "操作编码",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/cod/operate"
        }
    },
    {
        "code": "sample_issuse",
        "id": 1897802271294494,
        "name": "样品下发",
        "noteCn": "样品下发",
        "noteEn": "sample_issuse",
        "params": [
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "int",
                "defaultValue": null,
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "action_type",
                "paramName": "1：增加样品 2：删除样品",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "int",
                "defaultValue": "",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "",
                "noteEn": null,
                "paramCode": "hole_num",
                "paramName": "孔位：取值范围1-60（孔位不可重复）",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": null,
                "elementDataType": null,
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "sample_no",
                "paramName": "样品编号，唯一标识不可重复",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": null,
                "elementDataType": null,
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "sample_name",
                "paramName": "样品名称",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "int",
                "defaultValue": null,
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "sample_type",
                "paramName": "样品类型 1：未知样 2：水样 3：标样 4：空白样 5：质控样 6：平行样 7：加标回收样 8：校准点核查样",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "int",
                "defaultValue": null,
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "method_id",
                "paramName": "方法编码 1 : 15min消解-超低量程 2 : 15min消解-低量程  3 : 15min消解-高量程",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "sample_issuse",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "operate",
                "paramName": "操作类型",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/cod/operate"
        }
    },
    {
        "code": "obtain_result",
        "id": 1897802271294495,
        "name": "获取样品结果",
        "noteCn": "获取样品结果",
        "noteEn": "obtain_result",
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "obtain_result",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "operate",
                "paramName": "操作编码",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "int",
                        "defaultValue": null,
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "OUTPUT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "HoleNum",
                        "paramName": "孔位",
                        "property": null,
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    },
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "string",
                        "defaultValue": null,
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "OUTPUT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "SampleNo",
                        "paramName": "样品编码",
                        "property": null,
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    },
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "string",
                        "defaultValue": null,
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "OUTPUT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "Concentration",
                        "paramName": "浓度",
                        "property": null,
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    },
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "string",
                        "defaultValue": null,
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "OUTPUT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "ResultUnit",
                        "paramName": "浓度单位",
                        "property": null,
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    },
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "string",
                        "defaultValue": null,
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "OUTPUT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "TestStartTime",
                        "paramName": "分析开始时间",
                        "property": null,
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    },
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "string",
                        "defaultValue": null,
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "OUTPUT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "TestEndTime",
                        "paramName": "分析结束时间",
                        "property": null,
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    },
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "string",
                        "defaultValue": null,
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "OUTPUT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "Equation",
                        "paramName": "回归方程",
                        "property": null,
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    },
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "string",
                        "defaultValue": null,
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "OUTPUT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "DrawTime",
                        "paramName": "标曲绘制日期",
                        "property": null,
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    },
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "string",
                        "defaultValue": null,
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "OUTPUT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "Slope",
                        "paramName": "斜率",
                        "property": null,
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    },
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "string",
                        "defaultValue": null,
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "OUTPUT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "Intercept",
                        "paramName": "截距",
                        "property": null,
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    },
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "string",
                        "defaultValue": null,
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "OUTPUT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "r",
                        "paramName": "相关系数",
                        "property": null,
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    },
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "string",
                        "defaultValue": null,
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "OUTPUT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "ElementName",
                        "paramName": "因子名称",
                        "property": null,
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    }
                ],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "file",
                "defaultValue": null,
                "elementDataType": "",
                "flatten": false,
                "ioType": "OUTPUT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "result",
                "paramName": "测量结果",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/cod/operate"
        }
    },
    {
        "code": "clear_sample_list",
        "id": 1897802271294496,
        "name": "清空样品列表",
        "noteCn": "清空样品列表",
        "noteEn": "clear_sample_list",
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "clear_sample_list",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "operate",
                "paramName": "操作编码",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/cod/operate"
        }
    },
    {
        "code": "enter_sample_info",
        "id": 1897802271327232,
        "name": "录入样品信息",
        "noteCn": "录入样品信息",
        "noteEn": "enter_sample_info",
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "enter_sample_info",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "operate",
                "paramName": "指令编码",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "string",
                        "defaultValue": null,
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "INPUT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "sample_no",
                        "paramName": "样品编码",
                        "property": null,
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    },
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "string",
                        "defaultValue": null,
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "INPUT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "sample_name",
                        "paramName": "样品名称",
                        "property": null,
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    },
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": "ENUM",
                        "constraintValue": "[{\"label\":\"未知样\",\"value\":1},{\"label\":\"水样\",\"value\":2},{\"label\":\"标样\",\"value\":3},{\"label\":\"空白样\",\"value\":4},{\"label\":\"质控样\",\"value\":5},{\"label\":\"平行样\",\"value\":6},{\"label\":\"加标回收样\",\"value\":7},{\"label\":\"校准点核查样\",\"value\":8}]",
                        "constraintValueEn": "",
                        "dataType": "int",
                        "defaultValue": null,
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "INPUT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "sample_type",
                        "paramName": "样品类型",
                        "property": null,
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    },
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": "ENUM",
                        "constraintValue": "[{\"label\":\"15min消解-超低量程\",\"value\":1},{\"label\":\"15min消解-低量程\",\"value\":2},{\"label\":\"15min消解-高量程\",\"value\":3}]",
                        "constraintValueEn": "",
                        "dataType": "int",
                        "defaultValue": null,
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "INPUT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "method_id",
                        "paramName": "测量方法类型",
                        "property": null,
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    },
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": "RANGE",
                        "constraintValue": "(0,66]",
                        "constraintValueEn": "",
                        "dataType": "int",
                        "defaultValue": null,
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "INPUT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "slot_num",
                        "paramName": "孔位",
                        "property": null,
                        "required": 0,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    }
                ],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "array",
                "defaultValue": null,
                "elementDataType": "object",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "sample_info_list",
                "paramName": "样品信息列表",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/cod/operate"
        }
    },
    {
        "code": "wait_device_ready",
        "id": 1897802271327233,
        "name": "等待就绪",
        "noteCn": "等待就绪",
        "noteEn": "wait_device_ready",
        "params": null,
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/wait_device_ready"
        }
    },
    {
        "code": "send_sample_list",
        "id": 1897802271327234,
        "name": "批量下发样品",
        "noteCn": "批量下发样品",
        "noteEn": "send_sample_list",
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "send_sample_list",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "operate",
                "paramName": "批量下发样品",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/cod/operate"
        }
    },
    {
        "code": "wait_loop",
        "id": 1897802271327235,
        "name": "容器分配",
        "noteCn": "",
        "noteEn": "",
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "send_sample_list",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "operate",
                "paramName": "批量下发样品",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/cod/wait_loop"
        }
    }
]
        
        for action in actions_list:
            action_name = action.get("name", "")
            action_code = action.get("code", "")
            if (action_name and action_name.lower() in task_lower) or (action_code and action_code.lower() in task_lower):
                matched_actions.append({
                    "action_name": action_name,
                    "action_code": action_code,
                    "description": action.get("noteCn", "")
                })
        
        if matched_actions:
            result["matched_actions"] = matched_actions
            result["message"] = f"识别到 {len(matched_actions)} 个相关操作，请完善任务编排逻辑"
        
        return result
