"""
icpms_workstation 统一能力工作站工具类
设备名称: 等离子体质谱仪
设备描述: 电感耦合等离子体质谱仪是一种用于元素分析的高灵敏度仪器。它将样品引入高温等离子体中，使样品中的元素原子化并离子化，然后通过质谱仪对离子进行分离和检测。该仪器能够同时检测多种元素，并且具有极低的检测限，可检测到痕量甚至超痕量的元素。在环境监测、地质分析、生物医学等领域广泛应用。例如在环境样品中，可以检测重金属元素的含量；在生物医学研究中，可用于微量元素的代谢研究等。
生成时间: 2025-11-07 19:42:38
"""

class UnifiedWorkstationTools:
    """统一能力工作站工具管理器"""
    
    def tool_icpms_workstation(self, task_description: str, **params):
        """
        等离子体质谱仪 - 电感耦合等离子体质谱仪是一种用于元素分析的高灵敏度仪器。它将样品引入高温等离子体中，使样品中的元素原子化并离子化，然后通过质谱仪对离子进行分离和检测。该仪器能够同时检测多种元素，并且具有极低的检测限，可检测到痕量甚至超痕量的元素。在环境监测、地质分析、生物医学等领域广泛应用。例如在环境样品中，可以检测重金属元素的含量；在生物医学研究中，可用于微量元素的代谢研究等。
        
        可用操作:
        - 点火 (ignite): 点火
        - 分析启动 (analysisStart): 分析启动
        - 熄火 (flameout): 熄火
        - 分析停止 (analysisStop): 分析停止
        - 设置序列 (setSampleList): 设置序列
        - 批量录入样品信息 (entrySampleList): 批量录入样品信息
        - 开始分析样品（批量） (analysisListStart): 开始分析样品（批量）
        - 获取实验结果 (obtainResultList): 获取实验结果
        - 等待就绪 (wait_device_ready): 等待就绪
        - 容器分配 (wait_loop): None
        
        参数:
            task_description: 任务描述
            **params: 其他参数
        """
        # 根据任务描述执行相应的操作
        # 这里需要实现任务编排逻辑
        result = {
            "workstation": "等离子体质谱仪",
            "task": task_description,
            "status": "pending_implementation",
            "message": "任务编排功能待实现 - 需要根据任务描述解析并执行相应的动作序列"
        }
        
        # 简单的任务匹配逻辑
        task_lower = task_description.lower()
        
        # 尝试匹配已有的动作
        matched_actions = []
        actions_list = [
    {
        "code": "ignite",
        "id": 1897802271097858,
        "name": "点火",
        "noteCn": "点火",
        "noteEn": null,
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "ignite",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "operate",
                "paramName": "ignite",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/icpms/operate"
        }
    },
    {
        "code": "analysisStart",
        "id": 1897802271097859,
        "name": "分析启动",
        "noteCn": "分析启动",
        "noteEn": "",
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "anaysisStart",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "operate",
                "paramName": "指令编码",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "",
                "elementDataType": null,
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "sequence_id",
                "paramName": "序列ID",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "",
                "elementDataType": null,
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "sample_id",
                "paramName": "样品ID",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/icpms/operate"
        }
    },
    {
        "code": "flameout",
        "id": 1897802271097860,
        "name": "熄火",
        "noteCn": "熄火",
        "noteEn": "",
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "flameout",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "operate",
                "paramName": "熄火",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/icpms/operate"
        }
    },
    {
        "code": "analysisStop",
        "id": 1897802271097861,
        "name": "分析停止",
        "noteCn": "分析停止",
        "noteEn": null,
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "analysisStop",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "operate",
                "paramName": "指令编码",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": null,
                "elementDataType": null,
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "sequence_id",
                "paramName": "待分析序列id",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "",
                "elementDataType": null,
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "sample_id",
                "paramName": "待分析样品id",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/icpms/operate"
        }
    },
    {
        "code": "setSampleList",
        "id": 1897802271097862,
        "name": "设置序列",
        "noteCn": "设置序列",
        "noteEn": null,
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "setSampleList",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "operate",
                "paramName": "设置序列",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": null,
                "elementDataType": null,
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "sequence_name",
                "paramName": "序列名称",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "",
                "elementDataType": null,
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "method_id",
                "paramName": "方法id",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": null,
                "elementDataType": null,
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "sequence_id",
                "paramName": "序列id",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "string",
                        "defaultValue": null,
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "INPUT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "SampleName",
                        "paramName": "样品名称",
                        "property": null,
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    },
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "string",
                        "defaultValue": null,
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "INPUT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "SampleID",
                        "paramName": "样品id",
                        "property": null,
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    },
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "int",
                        "defaultValue": null,
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "INPUT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "SampleType",
                        "paramName": "样品类型0:空白(QC) 1:全定量标准 2:未知样品 3:QC样品",
                        "property": null,
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    },
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "int",
                        "defaultValue": null,
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "INPUT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "SamplePosition",
                        "paramName": "样品位置",
                        "property": null,
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    }
                ],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "array",
                "defaultValue": null,
                "elementDataType": "object",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "data",
                "paramName": "样品信息",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/icpms/operate"
        }
    },
    {
        "code": "entrySampleList",
        "id": 1897802271097863,
        "name": "批量录入样品信息",
        "noteCn": "批量录入样品信息",
        "noteEn": null,
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "entrySampleList",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "operate",
                "paramName": "指令编码",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "string",
                        "defaultValue": null,
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "INPUT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "sample_no",
                        "paramName": "样品id",
                        "property": null,
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    },
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": "RANGE",
                        "constraintValue": "(0,66]",
                        "constraintValueEn": "",
                        "dataType": "int",
                        "defaultValue": null,
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "INPUT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "slot_num",
                        "paramName": "孔位",
                        "property": null,
                        "required": 0,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    }
                ],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "array",
                "defaultValue": null,
                "elementDataType": "object",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "sample_info_list",
                "paramName": "样品信息列表",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "auto-sequence",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "sequence_name",
                "paramName": "序列名称",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "ENUM",
                "constraintValue": "[{\"label\":\"是\",\"value\":1},{\"label\":\"否\",\"value\":0}]",
                "constraintValueEn": "",
                "dataType": "int",
                "defaultValue": "1",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": null,
                "noteEn": "",
                "paramCode": "is_standard_running",
                "paramName": "是否运行标样",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/icpms/operate"
        }
    },
    {
        "code": "analysisListStart",
        "id": 1897802271097864,
        "name": "开始分析样品（批量）",
        "noteCn": "开始分析样品（批量）",
        "noteEn": null,
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "analysisListStart",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "operate",
                "paramName": "指令编码",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/icpms/operate"
        }
    },
    {
        "code": "obtainResultList",
        "id": 1897802271097865,
        "name": "获取实验结果",
        "noteCn": "获取实验结果",
        "noteEn": null,
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "obtainResultList",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "operate",
                "paramName": "获取实验结果",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/icpms/operate"
        }
    },
    {
        "code": "wait_device_ready",
        "id": 1897802271097866,
        "name": "等待就绪",
        "noteCn": "等待就绪",
        "noteEn": null,
        "params": null,
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/wait_device_ready"
        }
    },
    {
        "code": "wait_loop",
        "id": 1897802271097867,
        "name": "容器分配",
        "noteCn": null,
        "noteEn": null,
        "params": null,
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/icpms/wait_loop"
        }
    }
]
        
        for action in actions_list:
            action_name = action.get("name", "")
            action_code = action.get("code", "")
            if (action_name and action_name.lower() in task_lower) or (action_code and action_code.lower() in task_lower):
                matched_actions.append({
                    "action_name": action_name,
                    "action_code": action_code,
                    "description": action.get("noteCn", "")
                })
        
        if matched_actions:
            result["matched_actions"] = matched_actions
            result["message"] = f"识别到 {len(matched_actions)} 个相关操作，请完善任务编排逻辑"
        
        return result
