"""
lithography 统一能力工作站工具类
设备名称: 光刻工作站
设备描述: 纳米级三维激光直写 3D 打印设备（光刻胶专用）是一种高精度的微纳加工设备。它利用激光束对光刻胶进行逐点、逐层扫描曝光，通过控制激光的强度、扫描速度和曝光时间等参数，实现纳米级分辨率的三维结构制造。能够制造出复杂的微纳结构，如微纳光学器件、生物芯片、微机电系统等。该设备在微纳制造、生物医学工程、光学等领域具有重要应用，为这些领域的研究和产品开发提供了强大的微纳加工手段，推动了微纳技术的发展和应用。
生成时间: 2025-11-07 19:42:38
"""

class UnifiedWorkstationTools:
    """统一能力工作站工具管理器"""
    
    def tool_lithography(self, task_description: str, **params):
        """
        光刻工作站 - 纳米级三维激光直写 3D 打印设备（光刻胶专用）是一种高精度的微纳加工设备。它利用激光束对光刻胶进行逐点、逐层扫描曝光，通过控制激光的强度、扫描速度和曝光时间等参数，实现纳米级分辨率的三维结构制造。能够制造出复杂的微纳结构，如微纳光学器件、生物芯片、微机电系统等。该设备在微纳制造、生物医学工程、光学等领域具有重要应用，为这些领域的研究和产品开发提供了强大的微纳加工手段，推动了微纳技术的发展和应用。
        
        可用操作:
        - 选择通信串口 (init_communication): 选择通信串口
        - 出光 (laser_on): 出光
        - 取出样品 (take_samples): 取出样品
        - 打开真空吸盘 (open_vacuum_cupule): 打开真空吸盘
        - 关闭真空吸盘 (close_vacuum_cupule): 关闭真空吸盘
        - 开启相机 (open_camera): 开启相机
        - 设置投射照明值 (pos_light): 设置投射照明值
        - 抬升样品 (raise_stage): 抬升样品
        - 界面探测 (interface_detect): 界面探测
        - 载入样品 (load_samples): 载入样品
        - 开始光刻 (start_lithography): 开始光刻
        - 下降样品台 (down_stage): 下降样品台
        - 设置反射照明值 (neg_light): 设置反射照明值
        - 关闭相机 (close_camera): 关闭相机
        - 关门 (close_door): 关门
        - 开门 (open_door): 开门
        
        参数:
            task_description: 任务描述
            **params: 其他参数
        """
        # 根据任务描述执行相应的操作
        # 这里需要实现任务编排逻辑
        result = {
            "workstation": "光刻工作站",
            "task": task_description,
            "status": "pending_implementation",
            "message": "任务编排功能待实现 - 需要根据任务描述解析并执行相应的动作序列"
        }
        
        # 简单的任务匹配逻辑
        task_lower = task_description.lower()
        
        # 尝试匹配已有的动作
        matched_actions = []
        actions_list = [
    {
        "code": "init_communication",
        "id": 1897802271654912,
        "name": "选择通信串口",
        "noteCn": "选择通信串口",
        "noteEn": "init communication",
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "init_communication",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": "操作指令",
                "noteEn": null,
                "paramCode": "operation",
                "paramName": "操作指令",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "COM4",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "通信串口",
                "noteEn": null,
                "paramCode": "serial",
                "paramName": "通信串口",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/command"
        }
    },
    {
        "code": "laser_on",
        "id": 1897802271654913,
        "name": "出光",
        "noteCn": "出光",
        "noteEn": "laser on",
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "laser_on",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": "操作指令",
                "noteEn": null,
                "paramCode": "operation",
                "paramName": "操作指令",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "RANGE",
                "constraintValue": "[0,100]",
                "constraintValueEn": "",
                "dataType": "float",
                "defaultValue": "8",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "出光功率",
                "noteEn": "laser power",
                "paramCode": "laser_power",
                "paramName": "出光功率",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/command"
        }
    },
    {
        "code": "take_samples",
        "id": 1897802271654914,
        "name": "取出样品",
        "noteCn": "取出样品",
        "noteEn": "take samples",
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "take_samples",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": "操作指令",
                "noteEn": null,
                "paramCode": "operation",
                "paramName": "操作指令",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "RANGE",
                "constraintValue": "[-100,100]",
                "constraintValueEn": "",
                "dataType": "float",
                "defaultValue": "0",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "x取值（mm）",
                "noteEn": "",
                "paramCode": "x_to",
                "paramName": "x取值（mm）",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "RANGE",
                "constraintValue": "[-100,100]",
                "constraintValueEn": "",
                "dataType": "float",
                "defaultValue": "0",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "y取值（mm）",
                "noteEn": "",
                "paramCode": "y_to",
                "paramName": "y取值（mm）",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "RANGE",
                "constraintValue": "[-4.9,4.9]",
                "constraintValueEn": "",
                "dataType": "float",
                "defaultValue": "0",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "z取值（mm）",
                "noteEn": "",
                "paramCode": "z_move",
                "paramName": "z取值（mm）",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/command"
        }
    },
    {
        "code": "open_vacuum_cupule",
        "id": 1897802271654915,
        "name": "打开真空吸盘",
        "noteCn": "打开真空吸盘",
        "noteEn": "open vacuum cupule",
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "open_vacuum_cupule",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": "操作指令",
                "noteEn": null,
                "paramCode": "operation",
                "paramName": "操作指令",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/command"
        }
    },
    {
        "code": "close_vacuum_cupule",
        "id": 1897802271654916,
        "name": "关闭真空吸盘",
        "noteCn": "关闭真空吸盘",
        "noteEn": "close vacuum cupule",
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "close_vacuum_cupule",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": "操作指令",
                "noteEn": null,
                "paramCode": "operation",
                "paramName": "操作指令",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/command"
        }
    },
    {
        "code": "open_camera",
        "id": 1897802271654917,
        "name": "开启相机",
        "noteCn": "开启相机",
        "noteEn": "open camera",
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "open_camera",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": "操作指令",
                "noteEn": null,
                "paramCode": "operation",
                "paramName": "操作指令",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/command"
        }
    },
    {
        "code": "pos_light",
        "id": 1897802271654918,
        "name": "设置投射照明值",
        "noteCn": "设置投射照明值",
        "noteEn": "pos light",
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "pos_light",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": "操作指令",
                "noteEn": null,
                "paramCode": "operation",
                "paramName": "操作指令",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "RANGE",
                "constraintValue": "[0,99]",
                "constraintValueEn": "",
                "dataType": "int",
                "defaultValue": "0",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "照明值",
                "noteEn": null,
                "paramCode": "pos_value",
                "paramName": "照明值",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/command"
        }
    },
    {
        "code": "raise_stage",
        "id": 1897802271654919,
        "name": "抬升样品",
        "noteCn": "抬升样品",
        "noteEn": "raise stage",
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "raise_stage",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": "操作指令",
                "noteEn": null,
                "paramCode": "operation",
                "paramName": "操作指令",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "RANGE",
                "constraintValue": "[0,3000]",
                "constraintValueEn": "",
                "dataType": "int",
                "defaultValue": "1",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "抬升距离（um）",
                "noteEn": "raise distance",
                "paramCode": "distance",
                "paramName": "抬升距离（um）",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/command"
        }
    },
    {
        "code": "interface_detect",
        "id": 1897802271654920,
        "name": "界面探测",
        "noteCn": "界面探测",
        "noteEn": "interface detect",
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "interface_detect",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": "操作指令",
                "noteEn": null,
                "paramCode": "operation",
                "paramName": "操作指令",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "1105",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "方法名称",
                "noteEn": null,
                "paramCode": "method_name",
                "paramName": "方法名称",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "RANGE",
                "constraintValue": "[1,1000]",
                "constraintValueEn": "",
                "dataType": "float",
                "defaultValue": "90",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "起始位置（um）",
                "noteEn": null,
                "paramCode": "start_position",
                "paramName": "起始位置（um）",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "RANGE",
                "constraintValue": "[2,1000]",
                "constraintValueEn": "",
                "dataType": "float",
                "defaultValue": "60",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "z轴范围（um）",
                "noteEn": "z_range",
                "paramCode": "z_range",
                "paramName": "z轴范围（um）",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "RANGE",
                "constraintValue": "[-1,5]",
                "constraintValueEn": "",
                "dataType": "float",
                "defaultValue": "0.5",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "步进（um）",
                "noteEn": "z_step",
                "paramCode": "z_step",
                "paramName": "步进（um）",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "RANGE",
                "constraintValue": "[2,500]",
                "constraintValueEn": "",
                "dataType": "int",
                "defaultValue": "50",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "等待时间（ms）",
                "noteEn": "wait_time",
                "paramCode": "wait_time",
                "paramName": "等待时间（ms）",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "ENUM",
                "constraintValue": "[{\"label\":\"PZ\",\"value\":0},{\"label\":\"Z\",\"value\":1}]",
                "constraintValueEn": "",
                "dataType": "int",
                "defaultValue": "0",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "探测设备",
                "noteEn": "device_type",
                "paramCode": "device_type",
                "paramName": "探测设备",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "ENUM",
                "constraintValue": "[{\"label\":\"否\",\"value\":0},{\"label\":\"是\",\"value\":1}]",
                "constraintValueEn": "",
                "dataType": "int",
                "defaultValue": "0",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "auto_light",
                "noteEn": "auto_light",
                "paramCode": "auto_light",
                "paramName": "是否自动开启灯光",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "ENUM",
                "constraintValue": "[{\"label\":\"cross\",\"value\":0},{\"label\":\"circle\",\"value\":1},{\"label\":\"square\",\"value\":2}]",
                "constraintValueEn": "",
                "dataType": "int",
                "defaultValue": "0",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "探测形状",
                "noteEn": "detect_shape",
                "paramCode": "detect_shape",
                "paramName": "探测形状",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "RANGE",
                "constraintValue": "[1,90000]",
                "constraintValueEn": "",
                "dataType": "float",
                "defaultValue": "1000",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "范围（um）",
                "noteEn": "radius",
                "paramCode": "radius",
                "paramName": "范围（um）",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "ENUM",
                "constraintValue": "[{\"label\":\"Gaussion\",\"value\":0},{\"label\":\"Sigmoid\",\"value\":1}]",
                "constraintValueEn": "",
                "dataType": "int",
                "defaultValue": "1",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "计算核心",
                "noteEn": null,
                "paramCode": "fit_core",
                "paramName": "计算核心",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "ENUM",
                "constraintValue": "[{\"label\":\"3\",\"value\":3},{\"label\":\"5\",\"value\":5},{\"label\":\"7\",\"value\":7},{\"label\":\"9\",\"value\":9}]",
                "constraintValueEn": "",
                "dataType": "int",
                "defaultValue": "3",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "探测点个数",
                "noteEn": null,
                "paramCode": "detect_points_num",
                "paramName": "探测点个数",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": "",
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "RANGE",
                "constraintValue": "[-10,10]",
                "constraintValueEn": "",
                "dataType": "float",
                "defaultValue": "-0.02",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "调平参数x",
                "noteEn": null,
                "paramCode": "kx",
                "paramName": "调平参数x",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "RANGE",
                "constraintValue": "[-10,10]",
                "constraintValueEn": "",
                "dataType": "float",
                "defaultValue": "0.02",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "调平参数y",
                "noteEn": null,
                "paramCode": "ky",
                "paramName": "调平参数y",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "RANGE",
                "constraintValue": "[2,10]",
                "constraintValueEn": "",
                "dataType": "int",
                "defaultValue": "6",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "采样范围（pixel）",
                "noteEn": null,
                "paramCode": "win_size",
                "paramName": "采样范围（pixel）",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "ENUM",
                "constraintValue": "[{\"label\":\"主相机\",\"value\":0},{\"label\":\"探测相机\",\"value\":1},{\"label\":\"共聚焦相机\",\"value\":2}]",
                "constraintValueEn": "",
                "dataType": "int",
                "defaultValue": "0",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "相机类型",
                "noteEn": null,
                "paramCode": "camera_type",
                "paramName": "相机类型",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/command"
        }
    },
    {
        "code": "load_samples",
        "id": 1897802271654921,
        "name": "载入样品",
        "noteCn": "载入样品",
        "noteEn": "load samples",
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "load_samples",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": "操作指令",
                "noteEn": null,
                "paramCode": "operation",
                "paramName": "操作指令",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "RANGE",
                "constraintValue": "[-100,100]",
                "constraintValueEn": "",
                "dataType": "float",
                "defaultValue": "0.00",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "x取值（mm）",
                "noteEn": "",
                "paramCode": "x_to",
                "paramName": "x取值（mm）",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "RANGE",
                "constraintValue": "[-100,100]",
                "constraintValueEn": "",
                "dataType": "float",
                "defaultValue": "0.00",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "y取值（mm）",
                "noteEn": "",
                "paramCode": "y_to",
                "paramName": "y取值（mm）",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "RANGE",
                "constraintValue": "[-4.9,4.9]",
                "constraintValueEn": "",
                "dataType": "float",
                "defaultValue": "0.00",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "z取值（mm）",
                "noteEn": "",
                "paramCode": "z_move",
                "paramName": "z取值（mm）",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/command"
        }
    },
    {
        "code": "start_lithography",
        "id": 1897802271654922,
        "name": "开始光刻",
        "noteCn": "开始光刻",
        "noteEn": "start lithography",
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "start_lithography",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": "操作指令",
                "noteEn": null,
                "paramCode": "operation",
                "paramName": "操作指令",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "chem351LabLithographyScriptTemplate",
                "bindDataTypeProperty": "",
                "childParams": [
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "string",
                        "defaultValue": null,
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "INPUT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "id",
                        "paramName": "脚本",
                        "property": "id",
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    }
                ],
                "constraintType": "",
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "object",
                "defaultValue": "",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "运行脚本",
                "noteEn": "",
                "paramCode": "process_script",
                "paramName": "运行脚本",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": "",
                "unitTypeName": "",
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "",
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "4*4",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "预设加工矩阵",
                "noteEn": "",
                "paramCode": "matrix",
                "paramName": "预设加工矩阵",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "",
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "float",
                "defaultValue": "4000",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "基础加工速度",
                "noteEn": "",
                "paramCode": "base_speed",
                "paramName": "基础加工速度",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "float",
                "defaultValue": "1000",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "加工速度步进",
                "noteEn": null,
                "paramCode": "speed_step",
                "paramName": "加工速度步进",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "float",
                "defaultValue": "1",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "基础激光功率",
                "noteEn": null,
                "paramCode": "base_laser_power",
                "paramName": "基础激光功率",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "float",
                "defaultValue": "0.2",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "基础激光功率步进",
                "noteEn": null,
                "paramCode": "power_step",
                "paramName": "基础激光功率步进",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "resultCode",
                "elementDataType": null,
                "flatten": false,
                "ioType": "OUTPUT",
                "noteCn": null,
                "noteEn": "resultCode",
                "paramCode": "resultCode",
                "paramName": "resultCode",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/command"
        }
    },
    {
        "code": "down_stage",
        "id": 1897802271654923,
        "name": "下降样品台",
        "noteCn": "下降样品台",
        "noteEn": "raise stage",
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "down_stage",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": "操作指令",
                "noteEn": null,
                "paramCode": "operation",
                "paramName": "操作指令",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "RANGE",
                "constraintValue": "[0,3000]",
                "constraintValueEn": "",
                "dataType": "int",
                "defaultValue": "100",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "下降距离（um）",
                "noteEn": "down distance",
                "paramCode": "distance",
                "paramName": "下降距离（um）",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/command"
        }
    },
    {
        "code": "neg_light",
        "id": 1897802271654924,
        "name": "设置反射照明值",
        "noteCn": "设置反射照明值",
        "noteEn": "neg light",
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "neg_light",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": "操作指令",
                "noteEn": null,
                "paramCode": "operation",
                "paramName": "操作指令",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "RANGE",
                "constraintValue": "[0,99]",
                "constraintValueEn": "",
                "dataType": "int",
                "defaultValue": "0",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "照明值",
                "noteEn": null,
                "paramCode": "neg_value",
                "paramName": "照明值",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/command"
        }
    },
    {
        "code": "close_camera",
        "id": 1897802271654925,
        "name": "关闭相机",
        "noteCn": "关闭相机",
        "noteEn": "close camera",
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "close_camera",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": "操作指令",
                "noteEn": null,
                "paramCode": "operation",
                "paramName": "操作指令",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/command"
        }
    },
    {
        "code": "close_door",
        "id": 1897802271654926,
        "name": "关门",
        "noteCn": "关门",
        "noteEn": "close door",
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "close_door",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": "操作指令",
                "noteEn": null,
                "paramCode": "operation",
                "paramName": "操作指令",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/command"
        }
    },
    {
        "code": "open_door",
        "id": 1897802271654927,
        "name": "开门",
        "noteCn": "开门",
        "noteEn": "open door",
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "open_door",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": "操作指令",
                "noteEn": null,
                "paramCode": "operation",
                "paramName": "操作指令",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/command"
        }
    }
]
        
        for action in actions_list:
            action_name = action.get("name", "")
            action_code = action.get("code", "")
            if (action_name and action_name.lower() in task_lower) or (action_code and action_code.lower() in task_lower):
                matched_actions.append({
                    "action_name": action_name,
                    "action_code": action_code,
                    "description": action.get("noteCn", "")
                })
        
        if matched_actions:
            result["matched_actions"] = matched_actions
            result["message"] = f"识别到 {len(matched_actions)} 个相关操作，请完善任务编排逻辑"
        
        return result
