"""
photothermal_catalytic_reaction_workstation 统一能力工作站工具类
设备名称: 光热催化反应工作站
设备描述: 温度控制器是一种用于精确控制温度的设备。在实验室中，许多实验需要在特定的温度条件下进行，温度控制器能够实时监测环境或样品的温度，并根据设定的温度值自动调节加热或制冷设备的工作状态，使温度保持在设定的范围内。它具有高精度的温度控制功能，可以将温度波动控制在极小的范围内，确保实验在稳定的温度条件下进行。温度控制器可应用于各种需要温度控制的实验场景，如材料热处理、生物培养、化学反应等，为实验结果的准确性和可靠性提供重要保障。
生成时间: 2025-11-07 19:42:38
"""

class UnifiedWorkstationTools:
    """统一能力工作站工具管理器"""
    
    def tool_photothermal_catalytic_reaction_workstation(self, task_description: str, **params):
        """
        光热催化反应工作站 - 温度控制器是一种用于精确控制温度的设备。在实验室中，许多实验需要在特定的温度条件下进行，温度控制器能够实时监测环境或样品的温度，并根据设定的温度值自动调节加热或制冷设备的工作状态，使温度保持在设定的范围内。它具有高精度的温度控制功能，可以将温度波动控制在极小的范围内，确保实验在稳定的温度条件下进行。温度控制器可应用于各种需要温度控制的实验场景，如材料热处理、生物培养、化学反应等，为实验结果的准确性和可靠性提供重要保障。
        
        可用操作:
        - R轴转动 (R_axis_rotation): None
        - 开始光热催化 (start): None
        - 关闭所有仪器 (stop): None
        - R轴回零 (R_axis_init): None
        - 开启气体检测 (start_gas_monitoring): None
        - 开始通气 (start_three_channel_gas): None
        - 开启氙灯 (start_xenon_lamp): None
        - 开启温控仪 (start_temp_controller): None
        - 测试参数设置 (param_test): None
        - 无参数测试 (no_param): None
        
        参数:
            task_description: 任务描述
            **params: 其他参数
        """
        # 根据任务描述执行相应的操作
        # 这里需要实现任务编排逻辑
        result = {
            "workstation": "光热催化反应工作站",
            "task": task_description,
            "status": "pending_implementation",
            "message": "任务编排功能待实现 - 需要根据任务描述解析并执行相应的动作序列"
        }
        
        # 简单的任务匹配逻辑
        task_lower = task_description.lower()
        
        # 尝试匹配已有的动作
        matched_actions = []
        actions_list = [
    {
        "code": "R_axis_rotation",
        "id": 1897802271687697,
        "name": "R轴转动",
        "noteCn": null,
        "noteEn": null,
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "rotation_angle",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "operation",
                "paramName": "操作符",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "RANGE",
                "constraintValue": "[0,180]",
                "constraintValueEn": "",
                "dataType": "int",
                "defaultValue": "90",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "",
                "noteEn": null,
                "paramCode": "value",
                "paramName": "旋转角度",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": "°",
                "unitTypeName": "度",
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/command"
        }
    },
    {
        "code": "start",
        "id": 1897802271687698,
        "name": "开始光热催化",
        "noteCn": null,
        "noteEn": null,
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "start",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "operation",
                "paramName": "操作符",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "",
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "int",
                "defaultValue": "25",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "",
                "noteEn": null,
                "paramCode": "init_temp",
                "paramName": "起始温度",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": "℃",
                "unitTypeName": "摄氏度",
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "",
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "int",
                "defaultValue": "60",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "",
                "noteEn": null,
                "paramCode": "time",
                "paramName": "升温时间",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": "s",
                "unitTypeName": "秒",
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "",
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "int",
                "defaultValue": "400",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "",
                "noteEn": null,
                "paramCode": "final_temp",
                "paramName": "终止温度",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": "℃",
                "unitTypeName": "摄氏度",
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "",
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "int",
                "defaultValue": "10",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "",
                "noteEn": null,
                "paramCode": "set_ac",
                "paramName": "设置电流",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": "A",
                "unitTypeName": "安培",
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "RANGE",
                "constraintValue": "[2, 200]",
                "constraintValueEn": "",
                "dataType": "int",
                "defaultValue": "",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "",
                "noteEn": null,
                "paramCode": "set_channel_1",
                "paramName": "设置气体通道1流量",
                "property": null,
                "required": 0,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": "ml/min",
                "unitTypeName": "毫升每分钟",
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "RANGE",
                "constraintValue": "[2, 200]",
                "constraintValueEn": "",
                "dataType": "int",
                "defaultValue": "",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "",
                "noteEn": null,
                "paramCode": "set_channel_2",
                "paramName": "设置气体通道2流量",
                "property": null,
                "required": 0,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": "ml/min",
                "unitTypeName": "毫升每分钟",
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "RANGE",
                "constraintValue": "[2, 200]",
                "constraintValueEn": "",
                "dataType": "int",
                "defaultValue": "",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "",
                "noteEn": null,
                "paramCode": "set_channel_3",
                "paramName": "设置气体通道3流量",
                "property": null,
                "required": 0,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": "ml/min",
                "unitTypeName": "毫升每分钟",
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "",
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "int",
                "defaultValue": "",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "",
                "noteEn": null,
                "paramCode": "set_light_distance",
                "paramName": "设置光源高度",
                "property": null,
                "required": 0,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": "",
                "unitTypeName": "",
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/command"
        }
    },
    {
        "code": "stop",
        "id": 1897802271687699,
        "name": "关闭所有仪器",
        "noteCn": null,
        "noteEn": null,
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "stop",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "operation",
                "paramName": "操作符",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "file",
                "defaultValue": null,
                "elementDataType": "",
                "flatten": false,
                "ioType": "OUTPUT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "resultCode",
                "paramName": "resultCode",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/command"
        }
    },
    {
        "code": "R_axis_init",
        "id": 1897802271687700,
        "name": "R轴回零",
        "noteCn": null,
        "noteEn": null,
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "homing",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "operation",
                "paramName": "操作符",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "",
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "int",
                "defaultValue": "0",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "",
                "noteEn": null,
                "paramCode": "value",
                "paramName": "旋转角度",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": "°",
                "unitTypeName": "度",
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/command"
        }
    },
    {
        "code": "start_gas_monitoring",
        "id": 1897802271687701,
        "name": "开启气体检测",
        "noteCn": null,
        "noteEn": null,
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "gas_monitoring",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "operation",
                "paramName": "操作符",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "",
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "int",
                "defaultValue": "10",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "",
                "noteEn": null,
                "paramCode": "value",
                "paramName": "漏气流量值",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": "ppm",
                "unitTypeName": "",
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/command"
        }
    },
    {
        "code": "start_three_channel_gas",
        "id": 1897802271687702,
        "name": "开始通气",
        "noteCn": null,
        "noteEn": null,
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "start_three_channel",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "operation",
                "paramName": "操作符",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "RANGE",
                "constraintValue": "[2, 200]",
                "constraintValueEn": "",
                "dataType": "int",
                "defaultValue": "50",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "",
                "noteEn": null,
                "paramCode": "set_channel_1",
                "paramName": "设置气体通道1流量",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": "ml/min",
                "unitTypeName": "",
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "RANGE",
                "constraintValue": "[2, 200]",
                "constraintValueEn": "",
                "dataType": "int",
                "defaultValue": "50",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "",
                "noteEn": null,
                "paramCode": "set_channel_2",
                "paramName": "设置气体通道2流量",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": "ml/min",
                "unitTypeName": "",
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "RANGE",
                "constraintValue": "[2, 200]",
                "constraintValueEn": "",
                "dataType": "int",
                "defaultValue": "50",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "",
                "noteEn": null,
                "paramCode": "set_channel_3",
                "paramName": "设置气体通道3流量",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": "ml/min",
                "unitTypeName": "",
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/command"
        }
    },
    {
        "code": "start_xenon_lamp",
        "id": 1897802271687703,
        "name": "开启氙灯",
        "noteCn": null,
        "noteEn": null,
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "start_xenon_lamp",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "operation",
                "paramName": "操作符",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "",
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "int",
                "defaultValue": "15",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "",
                "noteEn": null,
                "paramCode": "current",
                "paramName": "电流",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": "A",
                "unitTypeName": "安培",
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/command"
        }
    },
    {
        "code": "start_temp_controller",
        "id": 1897802271687704,
        "name": "开启温控仪",
        "noteCn": null,
        "noteEn": null,
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "start_temp_controller",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "operation",
                "paramName": "操作符",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "",
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "int",
                "defaultValue": "25",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "",
                "noteEn": null,
                "paramCode": "init_temp",
                "paramName": "起始温度",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": "℃",
                "unitTypeName": "摄氏度",
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "",
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "int",
                "defaultValue": "60",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "",
                "noteEn": null,
                "paramCode": "time",
                "paramName": "升温时间",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": "min",
                "unitTypeName": "分钟",
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "",
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "int",
                "defaultValue": "500",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "",
                "noteEn": null,
                "paramCode": "target_temp",
                "paramName": "目标温度",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": "℃",
                "unitTypeName": "摄氏度",
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/command"
        }
    },
    {
        "code": "param_test",
        "id": 1897802271687705,
        "name": "测试参数设置",
        "noteCn": null,
        "noteEn": null,
        "params": [
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "float",
                        "defaultValue": "25",
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "INPUT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "initTemp",
                        "paramName": "初始温度",
                        "property": null,
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    },
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": [
                            {
                                "advanced": null,
                                "bindDataType": "",
                                "bindDataTypeProperty": null,
                                "childParams": [],
                                "constraintType": null,
                                "constraintValue": "",
                                "constraintValueEn": "",
                                "dataType": "float",
                                "defaultValue": "30",
                                "elementDataType": "",
                                "flatten": false,
                                "ioType": "INPUT",
                                "noteCn": null,
                                "noteEn": null,
                                "paramCode": "temp",
                                "paramName": "目标温度",
                                "property": null,
                                "required": 1,
                                "script": null,
                                "selection": null,
                                "selectorType": null,
                                "timeFlag": null,
                                "unitTypeCode": null,
                                "unitTypeName": null,
                                "value": null
                            },
                            {
                                "advanced": null,
                                "bindDataType": "",
                                "bindDataTypeProperty": null,
                                "childParams": [],
                                "constraintType": null,
                                "constraintValue": "",
                                "constraintValueEn": "",
                                "dataType": "float",
                                "defaultValue": "10",
                                "elementDataType": "",
                                "flatten": false,
                                "ioType": "INPUT",
                                "noteCn": null,
                                "noteEn": null,
                                "paramCode": "time",
                                "paramName": "升温时间",
                                "property": null,
                                "required": 1,
                                "script": null,
                                "selection": null,
                                "selectorType": null,
                                "timeFlag": null,
                                "unitTypeCode": null,
                                "unitTypeName": null,
                                "value": null
                            }
                        ],
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "array",
                        "defaultValue": null,
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "INPUT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "itemList",
                        "paramName": "温度参数",
                        "property": null,
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    }
                ],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "array",
                "defaultValue": null,
                "elementDataType": "object",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "others",
                "paramName": "指令",
                "property": null,
                "required": 0,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "",
            "url": ""
        }
    },
    {
        "code": "no_param",
        "id": 1897802271687706,
        "name": "无参数测试",
        "noteCn": null,
        "noteEn": null,
        "params": [
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": [
                            {
                                "advanced": null,
                                "bindDataType": "",
                                "bindDataTypeProperty": null,
                                "childParams": [],
                                "constraintType": "ENUM",
                                "constraintValue": "[{\"label\":\"极性强\",\"value\":0},{\"label\":\"极性中\",\"value\":1},{\"label\":\"极性弱\",\"value\":2}]",
                                "constraintValueEn": "",
                                "dataType": "int",
                                "defaultValue": null,
                                "elementDataType": "",
                                "flatten": false,
                                "ioType": "INPUT",
                                "noteCn": null,
                                "noteEn": null,
                                "paramCode": "Polarity",
                                "paramName": "Polarity",
                                "property": null,
                                "required": 1,
                                "script": null,
                                "selection": null,
                                "selectorType": null,
                                "timeFlag": null,
                                "unitTypeCode": null,
                                "unitTypeName": null,
                                "value": null
                            },
                            {
                                "advanced": null,
                                "bindDataType": "",
                                "bindDataTypeProperty": null,
                                "childParams": [],
                                "constraintType": "ENUM",
                                "constraintValue": "[{\"label\":\"容量小于10ml\",\"value\":0},{\"label\":\"容量 10-30ml\",\"value\":1},{\"label\":\"容量大于 30ml\",\"value\":2}]",
                                "constraintValueEn": "",
                                "dataType": "int",
                                "defaultValue": null,
                                "elementDataType": "",
                                "flatten": false,
                                "ioType": "INPUT",
                                "noteCn": null,
                                "noteEn": null,
                                "paramCode": "Capacity",
                                "paramName": "Capacity",
                                "property": null,
                                "required": 1,
                                "script": null,
                                "selection": null,
                                "selectorType": null,
                                "timeFlag": null,
                                "unitTypeCode": null,
                                "unitTypeName": null,
                                "value": null
                            }
                        ],
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "object",
                        "defaultValue": null,
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "INPUT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "ReactantOptions",
                        "paramName": "ReactantOptions",
                        "property": null,
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    },
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": [
                            {
                                "advanced": null,
                                "bindDataType": "",
                                "bindDataTypeProperty": null,
                                "childParams": [],
                                "constraintType": null,
                                "constraintValue": "",
                                "constraintValueEn": "",
                                "dataType": "int",
                                "defaultValue": "150",
                                "elementDataType": "",
                                "flatten": false,
                                "ioType": "INPUT",
                                "noteCn": null,
                                "noteEn": null,
                                "paramCode": "TargetTemperature",
                                "paramName": "TargetTemperature",
                                "property": null,
                                "required": 1,
                                "script": null,
                                "selection": null,
                                "selectorType": null,
                                "timeFlag": null,
                                "unitTypeCode": null,
                                "unitTypeName": null,
                                "value": null
                            },
                            {
                                "advanced": null,
                                "bindDataType": "",
                                "bindDataTypeProperty": null,
                                "childParams": [],
                                "constraintType": null,
                                "constraintValue": "",
                                "constraintValueEn": "",
                                "dataType": "int",
                                "defaultValue": "200",
                                "elementDataType": "",
                                "flatten": false,
                                "ioType": "INPUT",
                                "noteCn": null,
                                "noteEn": null,
                                "paramCode": "MaxPressure",
                                "paramName": "MaxPressure",
                                "property": null,
                                "required": 1,
                                "script": null,
                                "selection": null,
                                "selectorType": null,
                                "timeFlag": null,
                                "unitTypeCode": null,
                                "unitTypeName": null,
                                "value": null
                            }
                        ],
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "array",
                        "defaultValue": null,
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "INPUT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "Stages",
                        "paramName": "Stages",
                        "property": null,
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    }
                ],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "object",
                "defaultValue": null,
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "MicExpParam",
                "paramName": "MicExpParam",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "",
            "url": "/command"
        }
    }
]
        
        for action in actions_list:
            action_name = action.get("name", "")
            action_code = action.get("code", "")
            if (action_name and action_name.lower() in task_lower) or (action_code and action_code.lower() in task_lower):
                matched_actions.append({
                    "action_name": action_name,
                    "action_code": action_code,
                    "description": action.get("noteCn", "")
                })
        
        if matched_actions:
            result["matched_actions"] = matched_actions
            result["message"] = f"识别到 {len(matched_actions)} 个相关操作，请完善任务编排逻辑"
        
        return result
