"""
reaction_platform 统一能力工作站工具类
设备名称: 综合反应平台
设备描述: 液体加样平台是专门用于准确添加液体试剂的设备。它可以精确控制加样的体积，从微量到大量的液体都能实现精准加样。在生物与化学实验中，该平台广泛应用于细胞培养、PCR反应、药物筛选以及化合物管理等场景，可确保每个样品添加的试剂体积一致，提高实验的重复性和可靠性。其自动化的加样过程减少了人工操作的误差，提高了实验效率，是生物、化学等实验室常用的液体处理设备。
生成时间: 2025-11-07 19:42:38
"""

class UnifiedWorkstationTools:
    """统一能力工作站工具管理器"""
    
    def tool_reaction_platform(self, task_description: str, **params):
        """
        综合反应平台 - 液体加样平台是专门用于准确添加液体试剂的设备。它可以精确控制加样的体积，从微量到大量的液体都能实现精准加样。在生物与化学实验中，该平台广泛应用于细胞培养、PCR反应、药物筛选以及化合物管理等场景，可确保每个样品添加的试剂体积一致，提高实验的重复性和可靠性。其自动化的加样过程减少了人工操作的误差，提高了实验效率，是生物、化学等实验室常用的液体处理设备。
        
        可用操作:
        - 开始实验 (start): None
        - 稀释 (attenuation): None
        - 开始实验 (run): None
        - 初始化 (init): None
        
        参数:
            task_description: 任务描述
            **params: 其他参数
        """
        # 根据任务描述执行相应的操作
        # 这里需要实现任务编排逻辑
        result = {
            "workstation": "综合反应平台",
            "task": task_description,
            "status": "pending_implementation",
            "message": "任务编排功能待实现 - 需要根据任务描述解析并执行相应的动作序列"
        }
        
        # 简单的任务匹配逻辑
        task_lower = task_description.lower()
        
        # 尝试匹配已有的动作
        matched_actions = []
        actions_list = [
    {
        "code": "start",
        "id": 1897802271327240,
        "name": "开始实验",
        "noteCn": null,
        "noteEn": null,
        "params": [
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "file",
                "defaultValue": null,
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "file",
                "paramName": "配料表",
                "property": null,
                "required": 0,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "boolean",
                "defaultValue": null,
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "magneton",
                "paramName": "是否添加磁子",
                "property": null,
                "required": 0,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/"
        }
    },
    {
        "code": "attenuation",
        "id": 1897802271327241,
        "name": "稀释",
        "noteCn": null,
        "noteEn": null,
        "params": [
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "float",
                "defaultValue": null,
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "volume",
                "paramName": "吸取量",
                "property": null,
                "required": 0,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": null,
                "elementDataType": null,
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "diluent",
                "paramName": "稀释剂",
                "property": null,
                "required": 0,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "float",
                "defaultValue": null,
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "diluent-volume",
                "paramName": "稀释量",
                "property": null,
                "required": 0,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "boolean",
                "defaultValue": null,
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "filtration",
                "paramName": "是否过滤",
                "property": null,
                "required": 0,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/"
        }
    },
    {
        "code": "run",
        "id": 1897802271327242,
        "name": "开始实验",
        "noteCn": null,
        "noteEn": null,
        "params": [
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "",
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "boolean",
                "defaultValue": "true",
                "elementDataType": "",
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "start",
                "paramName": "operation",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "file",
                "defaultValue": null,
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "HiwoMatUrl",
                "paramName": "HIWO物料表",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "file",
                "defaultValue": "",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "HiwoTaskUrl",
                "paramName": "HIWO任务表",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "file",
                "defaultValue": null,
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "SowoMatUrl",
                "paramName": "SOWO物料表",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "file",
                "defaultValue": null,
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "SowoTaskUrl",
                "paramName": "SOWO任务表",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "file",
                "defaultValue": null,
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "StackMatUrl",
                "paramName": "堆栈物料表",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "ENUM",
                "constraintValue": "[{\"label\":\"不进行固体称量\", \"value\": 1},{\"label\":\"不进行液体进样\", \"value\": 2}, {\"label\":\"全流程\", \"value\": 3}]",
                "constraintValueEn": "",
                "dataType": "int",
                "defaultValue": "",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "RunMode",
                "paramName": "运行模式",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": "",
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "boolean",
                "defaultValue": "true",
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "MicUseFlag",
                "paramName": "是否使用微波",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": [
                            {
                                "advanced": null,
                                "bindDataType": "",
                                "bindDataTypeProperty": null,
                                "childParams": [],
                                "constraintType": "ENUM",
                                "constraintValue": "[{\"label\":\"极性强\",\"value\":0},{\"label\":\"极性中\",\"value\":1},{\"label\":\"极性弱\",\"value\":2}]",
                                "constraintValueEn": "",
                                "dataType": "int",
                                "defaultValue": null,
                                "elementDataType": "",
                                "flatten": false,
                                "ioType": "INPUT",
                                "noteCn": null,
                                "noteEn": null,
                                "paramCode": "Polarity",
                                "paramName": "极性",
                                "property": null,
                                "required": 1,
                                "script": null,
                                "selection": null,
                                "selectorType": null,
                                "timeFlag": null,
                                "unitTypeCode": null,
                                "unitTypeName": null,
                                "value": null
                            },
                            {
                                "advanced": null,
                                "bindDataType": "",
                                "bindDataTypeProperty": null,
                                "childParams": [],
                                "constraintType": "ENUM",
                                "constraintValue": "[{\"label\":\"容量小于10ml\",\"value\":0},{\"label\":\"容量 10-30ml\",\"value\":1},{\"label\":\"容量大于 30ml\",\"value\":2}]",
                                "constraintValueEn": "",
                                "dataType": "int",
                                "defaultValue": null,
                                "elementDataType": "",
                                "flatten": false,
                                "ioType": "INPUT",
                                "noteCn": null,
                                "noteEn": null,
                                "paramCode": "Capacity",
                                "paramName": "容量",
                                "property": null,
                                "required": 1,
                                "script": null,
                                "selection": null,
                                "selectorType": null,
                                "timeFlag": null,
                                "unitTypeCode": null,
                                "unitTypeName": null,
                                "value": null
                            }
                        ],
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "array",
                        "defaultValue": null,
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "INPUT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "ReactantOptions",
                        "paramName": "反应物选项结构",
                        "property": null,
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    },
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": "ENUM",
                        "constraintValue": "[{\"label\":\"高压实验\",\"value\":0},{\"label\":\"常压实验\",\"value\":1}]",
                        "constraintValueEn": "",
                        "dataType": "boolean",
                        "defaultValue": null,
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "INPUT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "ExperimentMode",
                        "paramName": "实验模式",
                        "property": null,
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    },
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": "RANGE",
                        "constraintValue": "[0,300]",
                        "constraintValueEn": "",
                        "dataType": "int",
                        "defaultValue": null,
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "INPUT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "MaxAllowedTemp",
                        "paramName": "实验最大允许温度(℃)",
                        "property": null,
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    },
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": "RANGE",
                        "constraintValue": "[1,600]",
                        "constraintValueEn": "",
                        "dataType": "int",
                        "defaultValue": null,
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "INPUT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "MaxAllowedPres",
                        "paramName": "实验最大允许压力(0.01MPa)",
                        "property": null,
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    },
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": [
                            {
                                "advanced": null,
                                "bindDataType": "",
                                "bindDataTypeProperty": null,
                                "childParams": [],
                                "constraintType": "RANGE",
                                "constraintValue": "[0,300]",
                                "constraintValueEn": "",
                                "dataType": "int",
                                "defaultValue": null,
                                "elementDataType": "",
                                "flatten": false,
                                "ioType": "INPUT",
                                "noteCn": null,
                                "noteEn": null,
                                "paramCode": "TargetTemperature",
                                "paramName": "目标温度(℃)",
                                "property": null,
                                "required": 1,
                                "script": null,
                                "selection": null,
                                "selectorType": null,
                                "timeFlag": null,
                                "unitTypeCode": null,
                                "unitTypeName": null,
                                "value": null
                            },
                            {
                                "advanced": null,
                                "bindDataType": "",
                                "bindDataTypeProperty": null,
                                "childParams": [],
                                "constraintType": "RANGE",
                                "constraintValue": "[1,600]",
                                "constraintValueEn": "",
                                "dataType": "int",
                                "defaultValue": null,
                                "elementDataType": "",
                                "flatten": false,
                                "ioType": "INPUT",
                                "noteCn": null,
                                "noteEn": null,
                                "paramCode": "MaxPressure",
                                "paramName": "最大压力(0.01MPa)",
                                "property": null,
                                "required": 1,
                                "script": null,
                                "selection": null,
                                "selectorType": null,
                                "timeFlag": null,
                                "unitTypeCode": null,
                                "unitTypeName": null,
                                "value": null
                            },
                            {
                                "advanced": null,
                                "bindDataType": "",
                                "bindDataTypeProperty": null,
                                "childParams": [],
                                "constraintType": "RANGE",
                                "constraintValue": "[1,86400]",
                                "constraintValueEn": "",
                                "dataType": "int",
                                "defaultValue": null,
                                "elementDataType": "",
                                "flatten": false,
                                "ioType": "INPUT",
                                "noteCn": null,
                                "noteEn": null,
                                "paramCode": "HeatUpTime",
                                "paramName": "升温时间(s)",
                                "property": null,
                                "required": 1,
                                "script": null,
                                "selection": null,
                                "selectorType": null,
                                "timeFlag": null,
                                "unitTypeCode": null,
                                "unitTypeName": null,
                                "value": null
                            },
                            {
                                "advanced": null,
                                "bindDataType": "",
                                "bindDataTypeProperty": null,
                                "childParams": [],
                                "constraintType": "RANGE",
                                "constraintValue": "[1,86400]",
                                "constraintValueEn": "",
                                "dataType": "int",
                                "defaultValue": null,
                                "elementDataType": "",
                                "flatten": false,
                                "ioType": "INPUT",
                                "noteCn": null,
                                "noteEn": null,
                                "paramCode": "HoldTime",
                                "paramName": "保持时间(s)",
                                "property": null,
                                "required": 1,
                                "script": null,
                                "selection": null,
                                "selectorType": null,
                                "timeFlag": null,
                                "unitTypeCode": null,
                                "unitTypeName": null,
                                "value": null
                            },
                            {
                                "advanced": null,
                                "bindDataType": "",
                                "bindDataTypeProperty": null,
                                "childParams": [],
                                "constraintType": "RANGE",
                                "constraintValue": "[0,650]",
                                "constraintValueEn": "",
                                "dataType": "int",
                                "defaultValue": null,
                                "elementDataType": "",
                                "flatten": false,
                                "ioType": "INPUT",
                                "noteCn": null,
                                "noteEn": null,
                                "paramCode": "Power",
                                "paramName": "Power(W)",
                                "property": null,
                                "required": 1,
                                "script": null,
                                "selection": null,
                                "selectorType": null,
                                "timeFlag": null,
                                "unitTypeCode": null,
                                "unitTypeName": null,
                                "value": null
                            }
                        ],
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "array",
                        "defaultValue": null,
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "INPUT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "Stages",
                        "paramName": "实验阶段",
                        "property": null,
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    }
                ],
                "constraintType": "",
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "array",
                "defaultValue": "true",
                "elementDataType": "object",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "MicExpParam",
                "paramName": "微波参数",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "file",
                "defaultValue": null,
                "elementDataType": "",
                "flatten": false,
                "ioType": "OUTPUT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "resultCode",
                "paramName": "结果文件",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/StartExperiment"
        }
    },
    {
        "code": "init",
        "id": 1897802271327243,
        "name": "初始化",
        "noteCn": null,
        "noteEn": null,
        "params": null,
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/Init"
        }
    }
]
        
        for action in actions_list:
            action_name = action.get("name", "")
            action_code = action.get("code", "")
            if (action_name and action_name.lower() in task_lower) or (action_code and action_code.lower() in task_lower):
                matched_actions.append({
                    "action_name": action_name,
                    "action_code": action_code,
                    "description": action.get("noteCn", "")
                })
        
        if matched_actions:
            result["matched_actions"] = matched_actions
            result["message"] = f"识别到 {len(matched_actions)} 个相关操作，请完善任务编排逻辑"
        
        return result
