"""
spps_workstation 统一能力工作站工具类
设备名称: 固相多肽工作站
设备描述: 固相多肽合成仪是用于人工合成多肽的设备。它基于固相合成的原理，将氨基酸逐个连接到固相载体上，通过不断重复脱保护、缩合等反应步骤，合成具有特定序列的多肽。在药物研发中，可合成具有生物活性的多肽药物；在蛋白质结构和功能研究中，可合成用于研究的多肽片段。其自动化的合成过程提高了合成效率和多肽的纯度，为多肽相关的研究和应用提供了有力的支持。
生成时间: 2025-11-07 19:42:38
"""

class UnifiedWorkstationTools:
    """统一能力工作站工具管理器"""
    
    def tool_spps_workstation(self, task_description: str, **params):
        """
        固相多肽工作站 - 固相多肽合成仪是用于人工合成多肽的设备。它基于固相合成的原理，将氨基酸逐个连接到固相载体上，通过不断重复脱保护、缩合等反应步骤，合成具有特定序列的多肽。在药物研发中，可合成具有生物活性的多肽药物；在蛋白质结构和功能研究中，可合成用于研究的多肽片段。其自动化的合成过程提高了合成效率和多肽的纯度，为多肽相关的研究和应用提供了有力的支持。
        
        可用操作:
        - 开始合成 (start_synthesizer): 开始合成
        - 转动合成仪 (rotating_synthesizer): 转动合成仪
        - 合成仪取料结束 (get_synthesizer_rotating_ret): 合成仪取料结束
        - 转动裂解仪 (rotating_pyrolyzer): 转动裂解仪
        - 裂解仪取料结束 (get_pyrolyzer_rotating_ret): 裂解仪取料结束
        - 合成仪关门 (close_synthesizer): 合成仪关门
        - 裂解仪关门 (close_pyrolyzer): 裂解仪关门
        - 裂解仪离心管锁扣下移 (down_pyrolyzer_lock): 裂解仪离心管锁扣下移
        - 获取裂解仪离心管锁扣上移结果 (get_upward_pyrolyzer_lock_ret): 获取裂解仪离心管锁扣上移结果
        - 获取裂解仪离心管锁扣下移结果 (get_down_pyrolyzer_lock_ret): 获取裂解仪离心管锁扣下移结果
        - 裂解仪离心管锁扣上移 (upward_pyrolyzer_lock): 裂解仪离心管锁扣上移
        - 开始裂解 (start_pyrolyzer): 开始裂解
        - 开始裂解前处理 (pre_start_pyrolyzer): 开始裂解前处理
        - 测试指令 (test_cmd): test cmd
        
        参数:
            task_description: 任务描述
            **params: 其他参数
        """
        # 根据任务描述执行相应的操作
        # 这里需要实现任务编排逻辑
        result = {
            "workstation": "固相多肽工作站",
            "task": task_description,
            "status": "pending_implementation",
            "message": "任务编排功能待实现 - 需要根据任务描述解析并执行相应的动作序列"
        }
        
        # 简单的任务匹配逻辑
        task_lower = task_description.lower()
        
        # 尝试匹配已有的动作
        matched_actions = []
        actions_list = [
    {
        "code": "start_synthesizer",
        "id": 1897802271392780,
        "name": "开始合成",
        "noteCn": "开始合成",
        "noteEn": null,
        "params": [
            {
                "advanced": null,
                "bindDataType": "chemBioLabTemplate",
                "bindDataTypeProperty": "",
                "childParams": [
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "int",
                        "defaultValue": null,
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "INPUT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "id",
                        "paramName": "主键",
                        "property": "id",
                        "required": 0,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    },
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "string",
                        "defaultValue": null,
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "INPUT",
                        "noteCn": "合成模板名称",
                        "noteEn": null,
                        "paramCode": "modelName",
                        "paramName": "模板名称",
                        "property": "modelName",
                        "required": 0,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    },
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": "ENUM",
                        "constraintValue": "[{\"label\":\"加载并启动\",\"value\":1},{\"label\":\"只加载不启动\",\"value\":0}]",
                        "constraintValueEn": "",
                        "dataType": "int",
                        "defaultValue": "1",
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "INPUT",
                        "noteCn": "启动类型",
                        "noteEn": null,
                        "paramCode": "LoadAndStart",
                        "paramName": "启动类型",
                        "property": "",
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": "",
                        "unitTypeName": "",
                        "value": null
                    },
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "int",
                        "defaultValue": "0",
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "CONSTANT",
                        "noteCn": "运行模式",
                        "noteEn": "run mode",
                        "paramCode": "OperatingMode",
                        "paramName": "运行模式",
                        "property": "",
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    },
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "int",
                        "defaultValue": "1",
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "CONSTANT",
                        "noteCn": "是否运行未完成的项目",
                        "noteEn": "run unfinished",
                        "paramCode": "UnfinishedContinue",
                        "paramName": "是否运行未完成的项目",
                        "property": "",
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    },
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "int",
                        "defaultValue": "96",
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "CONSTANT",
                        "noteCn": "通道",
                        "noteEn": "",
                        "paramCode": "channel",
                        "paramName": "通道",
                        "property": "",
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": "",
                        "unitTypeName": null,
                        "value": null
                    }
                ],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "array",
                "defaultValue": null,
                "elementDataType": "object",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "开始合成",
                "noteEn": null,
                "paramCode": "others",
                "paramName": "开始合成",
                "property": null,
                "required": 0,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": "",
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "startProject",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": "启动项目",
                "noteEn": "",
                "paramCode": "cmd",
                "paramName": "操作指令",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/chemist/script/unionTides"
        }
    },
    {
        "code": "rotating_synthesizer",
        "id": 1897802271392781,
        "name": "转动合成仪",
        "noteCn": "转动合成仪",
        "noteEn": "",
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "takeOrPlaceTube",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": "转动合成仪",
                "noteEn": "",
                "paramCode": "cmd",
                "paramName": "操作指令",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": 0,
                "bindDataType": "",
                "bindDataTypeProperty": "",
                "childParams": [
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "int",
                        "defaultValue": "96",
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "CONSTANT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "channel",
                        "paramName": "通道",
                        "property": null,
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    }
                ],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "array",
                "defaultValue": "[{\"channel\":96}]",
                "elementDataType": "object",
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "others",
                "paramName": "通道类别",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/chemist/script/unionTides"
        }
    },
    {
        "code": "get_synthesizer_rotating_ret",
        "id": 1897802271392782,
        "name": "合成仪取料结束",
        "noteCn": "合成仪取料结束",
        "noteEn": null,
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "takeOrPlaceTubeEnd",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": "合成仪取料结束",
                "noteEn": null,
                "paramCode": "cmd",
                "paramName": "操作指令",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "int",
                        "defaultValue": "96",
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "CONSTANT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "channel",
                        "paramName": "通道",
                        "property": null,
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": "",
                        "unitTypeName": null,
                        "value": null
                    },
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "int",
                        "defaultValue": "4",
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "INPUT",
                        "noteCn": "等待取料完成时间（s）",
                        "noteEn": null,
                        "paramCode": "sleepTime",
                        "paramName": "等待取料完成时间（s）",
                        "property": null,
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    }
                ],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "array",
                "defaultValue": "[{\"channel\":96}]",
                "elementDataType": "object",
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "others",
                "paramName": "参数",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/chemist/script/unionTides"
        }
    },
    {
        "code": "rotating_pyrolyzer",
        "id": 1897802271392783,
        "name": "转动裂解仪",
        "noteCn": "转动裂解仪",
        "noteEn": "",
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "takeOrPlaceTube",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": "转动裂解仪",
                "noteEn": "",
                "paramCode": "cmd",
                "paramName": "操作指令",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "int",
                        "defaultValue": "24",
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "CONSTANT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "channel",
                        "paramName": "通道",
                        "property": null,
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    }
                ],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "array",
                "defaultValue": "[{\"channel\":24}]",
                "elementDataType": "object",
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "others",
                "paramName": "参数",
                "property": null,
                "required": 0,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/chemist/script/unionTides"
        }
    },
    {
        "code": "get_pyrolyzer_rotating_ret",
        "id": 1897802271392784,
        "name": "裂解仪取料结束",
        "noteCn": "裂解仪取料结束",
        "noteEn": null,
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "takeOrPlaceTubeEnd",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": "裂解仪取料结束",
                "noteEn": null,
                "paramCode": "cmd",
                "paramName": "操作指令",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "int",
                        "defaultValue": "24",
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "CONSTANT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "channel",
                        "paramName": "通道",
                        "property": null,
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    },
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "int",
                        "defaultValue": "5",
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "INPUT",
                        "noteCn": "等待取料完成时间（s）",
                        "noteEn": null,
                        "paramCode": "sleepTime",
                        "paramName": "等待取料完成时间（s）",
                        "property": null,
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    }
                ],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "array",
                "defaultValue": "[{\"channel\":24}]",
                "elementDataType": "object",
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": "参数",
                "noteEn": null,
                "paramCode": "others",
                "paramName": "参数",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/chemist/script/unionTides"
        }
    },
    {
        "code": "close_synthesizer",
        "id": 1897802271392785,
        "name": "合成仪关门",
        "noteCn": "合成仪关门",
        "noteEn": "",
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "close_synthesizer",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": "合成仪关门",
                "noteEn": "",
                "paramCode": "operation",
                "paramName": "操作指令",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/chemist/script/unionTides"
        }
    },
    {
        "code": "close_pyrolyzer",
        "id": 1897802271392786,
        "name": "裂解仪关门",
        "noteCn": "裂解仪关门",
        "noteEn": "",
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "close_pyrolyzer",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": "裂解仪关门",
                "noteEn": "",
                "paramCode": "operation",
                "paramName": "操作指令",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/chemist/script/unionTides"
        }
    },
    {
        "code": "down_pyrolyzer_lock",
        "id": 1897802271392787,
        "name": "裂解仪离心管锁扣下移",
        "noteCn": "裂解仪离心管锁扣下移",
        "noteEn": null,
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "down_pyrolyzer_lock",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": "裂解仪离心管锁扣下移",
                "noteEn": null,
                "paramCode": "operation",
                "paramName": "操作指令",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/chemist/script/unionTides"
        }
    },
    {
        "code": "get_upward_pyrolyzer_lock_ret",
        "id": 1897802271392788,
        "name": "获取裂解仪离心管锁扣上移结果",
        "noteCn": "获取裂解仪离心管锁扣上移结果",
        "noteEn": null,
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "get_upward_pyrolyzer_lock_ret",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": "获取裂解仪离心管锁扣上移结果",
                "noteEn": null,
                "paramCode": "operation",
                "paramName": "操作指令",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/chemist/script/unionTides"
        }
    },
    {
        "code": "get_down_pyrolyzer_lock_ret",
        "id": 1897802271392789,
        "name": "获取裂解仪离心管锁扣下移结果",
        "noteCn": "获取裂解仪离心管锁扣下移结果",
        "noteEn": null,
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "get_down_pyrolyzer_lock_ret",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": "获取裂解仪离心管锁扣下移结果",
                "noteEn": null,
                "paramCode": "operation",
                "paramName": "操作指令",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/chemist/script/unionTides"
        }
    },
    {
        "code": "upward_pyrolyzer_lock",
        "id": 1897802271392790,
        "name": "裂解仪离心管锁扣上移",
        "noteCn": "裂解仪离心管锁扣上移",
        "noteEn": "",
        "params": [
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "openLid",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": "裂解仪关门",
                "noteEn": "",
                "paramCode": "cmd",
                "paramName": "操作指令",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "int",
                        "defaultValue": "24",
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "CONSTANT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "channel",
                        "paramName": "通道",
                        "property": null,
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    }
                ],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "array",
                "defaultValue": "[{\"channel\":24}]",
                "elementDataType": "object",
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": null,
                "noteEn": null,
                "paramCode": "others",
                "paramName": "参数",
                "property": null,
                "required": 0,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/chemist/script/unionTides"
        }
    },
    {
        "code": "start_pyrolyzer",
        "id": 1897802271392791,
        "name": "开始裂解",
        "noteCn": "开始裂解",
        "noteEn": null,
        "params": [
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": "",
                "childParams": [
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": "ENUM",
                        "constraintValue": "[{\"label\":\"加载并启动\",\"value\":1},{\"label\":\"只加载不启动\",\"value\":0}]",
                        "constraintValueEn": "",
                        "dataType": "int",
                        "defaultValue": "1",
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "INPUT",
                        "noteCn": "启动类型",
                        "noteEn": null,
                        "paramCode": "LoadAndStart",
                        "paramName": "启动类型",
                        "property": "",
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": "",
                        "unitTypeName": "",
                        "value": null
                    },
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "int",
                        "defaultValue": "0",
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "CONSTANT",
                        "noteCn": "运行模式",
                        "noteEn": "run mode",
                        "paramCode": "OperatingMode",
                        "paramName": "运行模式",
                        "property": "",
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    },
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "int",
                        "defaultValue": "1",
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "CONSTANT",
                        "noteCn": "是否运行未完成的项目",
                        "noteEn": "run unfinished",
                        "paramCode": "UnfinishedContinue",
                        "paramName": "是否运行未完成的项目",
                        "property": "",
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    },
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "int",
                        "defaultValue": "24",
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "CONSTANT",
                        "noteCn": "通道",
                        "noteEn": "",
                        "paramCode": "channel",
                        "paramName": "通道",
                        "property": "",
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": "",
                        "unitTypeName": null,
                        "value": null
                    }
                ],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "array",
                "defaultValue": "[{\"LoadAndStart\":0,\"OperatingMode\":0,\"UnfinishedContinue\":1,\"channel\":24}]",
                "elementDataType": "object",
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": "开始裂解",
                "noteEn": null,
                "paramCode": "others",
                "paramName": "开始裂解",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": "",
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "startProject",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": "启动项目",
                "noteEn": "",
                "paramCode": "cmd",
                "paramName": "操作指令",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/chemist/script/unionTides"
        }
    },
    {
        "code": "pre_start_pyrolyzer",
        "id": 1897802271392792,
        "name": "开始裂解前处理",
        "noteCn": "开始裂解前处理",
        "noteEn": null,
        "params": [
            {
                "advanced": null,
                "bindDataType": "chemBioPyrolyzerTemplate",
                "bindDataTypeProperty": "",
                "childParams": [
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "int",
                        "defaultValue": null,
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "INPUT",
                        "noteCn": null,
                        "noteEn": null,
                        "paramCode": "id",
                        "paramName": "主键",
                        "property": "id",
                        "required": 0,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    },
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "string",
                        "defaultValue": null,
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "INPUT",
                        "noteCn": "裂解模板名称",
                        "noteEn": null,
                        "paramCode": "modelName",
                        "paramName": "裂解模板名称",
                        "property": "modelName",
                        "required": 0,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": null,
                        "unitTypeName": null,
                        "value": null
                    },
                    {
                        "advanced": null,
                        "bindDataType": null,
                        "bindDataTypeProperty": null,
                        "childParams": null,
                        "constraintType": null,
                        "constraintValue": "",
                        "constraintValueEn": "",
                        "dataType": "int",
                        "defaultValue": "0",
                        "elementDataType": null,
                        "flatten": false,
                        "ioType": "CONSTANT",
                        "noteCn": "通道",
                        "noteEn": "",
                        "paramCode": "channel",
                        "paramName": "通道",
                        "property": "",
                        "required": 1,
                        "script": null,
                        "selection": null,
                        "selectorType": null,
                        "timeFlag": null,
                        "unitTypeCode": "",
                        "unitTypeName": null,
                        "value": null
                    }
                ],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "array",
                "defaultValue": null,
                "elementDataType": "object",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "开始裂解",
                "noteEn": null,
                "paramCode": "others",
                "paramName": "开始裂解",
                "property": null,
                "required": 0,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": "",
                "unitTypeName": null,
                "value": null
            },
            {
                "advanced": null,
                "bindDataType": null,
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "string",
                "defaultValue": "startProject",
                "elementDataType": null,
                "flatten": false,
                "ioType": "CONSTANT",
                "noteCn": "启动项目",
                "noteEn": "",
                "paramCode": "cmd",
                "paramName": "操作指令",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/chemist/script/unionTides"
        }
    },
    {
        "code": "test_cmd",
        "id": 1897802271392793,
        "name": "测试指令",
        "noteCn": "test cmd",
        "noteEn": "",
        "params": [
            {
                "advanced": null,
                "bindDataType": "",
                "bindDataTypeProperty": null,
                "childParams": [],
                "constraintType": null,
                "constraintValue": "",
                "constraintValueEn": "",
                "dataType": "int",
                "defaultValue": null,
                "elementDataType": "",
                "flatten": false,
                "ioType": "INPUT",
                "noteCn": "count",
                "noteEn": null,
                "paramCode": "count",
                "paramName": "count",
                "property": null,
                "required": 1,
                "script": null,
                "selection": null,
                "selectorType": null,
                "timeFlag": null,
                "unitTypeCode": null,
                "unitTypeName": null,
                "value": null
            }
        ],
        "recommend": null,
        "translator": "default",
        "translatorArgs": {
            "method": "POST",
            "url": "/command"
        }
    }
]
        
        for action in actions_list:
            action_name = action.get("name", "")
            action_code = action.get("code", "")
            if (action_name and action_name.lower() in task_lower) or (action_code and action_code.lower() in task_lower):
                matched_actions.append({
                    "action_name": action_name,
                    "action_code": action_code,
                    "description": action.get("noteCn", "")
                })
        
        if matched_actions:
            result["matched_actions"] = matched_actions
            result["message"] = f"识别到 {len(matched_actions)} 个相关操作，请完善任务编排逻辑"
        
        return result
